services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
